### ISSUE TITLE
pyslurm import error 

### ISSUE THREAD

**Issue by hokiegeek2** [PySlurm/pyslurm#226]
#### Details

* Slurm Version: 20.8.11
* Python Version: 3.9.7
* Cython Version: 0.29.24
* PySlurm Branch: main
* Linux Distribution: Ubuntu 18.04

#### Issue

After successfully building (I think)...

![image](https://user-images.githubusercontent.com/10785153/151365477-850c493b-8b6a-4bcc-a820-2b2049bbedd8.png)

...and installing pyslurm (I think)...

![image](https://user-images.githubusercontent.com/10785153/151365850-bc7c5952-ff7d-4202-9b78-171e3f6ec1db.png)

when I attempt to import pyslurm I get this error:

![image](https://user-images.githubusercontent.com/10785153/151365235-48d0a542-8a3f-4200-b315-38fe0115f521.png)

**Comment by hokiegeek2** [comment]
Also, when I attempt the pyslurm install from the 20.11.8 branch or tag I get the following version error:

![image](https://user-images.githubusercontent.com/10785153/151368506-82250653-9f4f-4b50-9646-b3ed0ed5b2c1.png)

**Comment by schluenz** [comment]
pyslurm 20.11.8 install and run works fine for me. I think the "no module named pyslurm.pyslurm" error is simply due to cwd in pyslurm (which contains a folder pyslurm). 
```
python3 -c 'import pyslurm; print(pyslurm.__version__)'
20.11.8.0
cd pyslurm-20.11.8-1/
python3 -c 'import pyslurm; print(pyslurm.__version__)'
ModuleNotFoundError: No module named 'pyslurm.pyslurm'
```

**Comment by tazend** [comment]
As @schluenz hinted, the original import error stems from the fact that python, by default, always searches for modules/packages inside the current working directory first (see [here](https://docs.python.org/3/library/sys.html#sys.path)). So if you do `import pyslurm` from the top-directory in the repo, you will receive this import error, because there is actually no `pyslurm.py` in the `pyslurm` directory

The import would probably work for a ordinary python project, but since pyslurm consists of almost only `*.pyx` files that have to be compiled first, it won't work. It would work with an editable install, or, since python 3.11 there is a new command-line flag [-P](https://docs.python.org/3/using/cmdline.html#cmdoption-P) that prevents prepending the cwd.

So importing the pyslurm library will work from anywhere but the top-directory in the git repo
