### ISSUE TITLE
Slurm job submit with "--phx-priority" error

### ISSUE THREAD

**Issue by huochaitiantang** [PySlurm/pyslurm#249]
When I try to submit a job by the code like https://github.com/PySlurm/pyslurm/blob/main/tests/test_job.py#L10-L25
There is an error:
```
python: error: job must not use --phx-priority when user priority is none.
Traceback (most recent call last):
  File "test_job.py", line 22, in <module>
    test_job_submit()
  File "test_job.py", line 13, in test_job_submit
    test_job_id = pyslurm.job().submit_batch_job(test_job)
  File "pyslurm/pyslurm.pyx", line 2786, in pyslurm.pyslurm.job.submit_batch_job
ValueError: ('Batch job submission failed: %s', None)
```
Is there any solution? 
Thanks!

**Comment by tazend** [comment]
Hi @huochaitiantang 

Could please also provide the following information?

* Slurm Version
* Python Version
* Cython Version
* PySlurm Branch
* Linux Distribution

Is this message showing on a local slurm installation, or on a HPC-Cluster you are using? If it is the latter, I believe this error might be a message returned from a custom job-submit plugin that is installed.

What happens if you submit a job like this with `sbatch` (same properties as the pyslurm test job):

```
sbatch -J pyslurm_test_job -n 2 -c 3 --wrap="sleep 3600"
```

Is the error message also showing when using sbatch?

**Comment by huochaitiantang** [comment]
> Is this message showing on a local slurm installation, or on a HPC-Cluster you are using? If it is the latter, I believe this error might be a message returned from a custom job-submit plugin that is installed.

Yes, you are right.
I have found some extra parameters (eg. --phx-priority) in our custom slurm.
Thank you very much!
