### ISSUE TITLE
How can I make slurm.conf if I use multiple dockers (not using localhost)

### ISSUE THREAD

**Issue by SuminHan** [PySlurm/pyslurm#85]
I've referenced this page: https://github.com/PySlurm/pyslurm/wiki/Testing-PySlurm-with-Docker
And I guess this article is only about the slurm in the localhost.
I want to construct the system where multiple dockers communicate through MPI, so my configuration file of slurm.conf may need some IP address for each docker container, right?
Can you show me some helping materials to configure this environment?

**Comment by giovtorres** [comment]
I setup this container with Slurm precompiled inside so that I can clone the PySlurm repo inside the container, compile/install, and do some basic unit tests.  It was only meant to get access to the Slurm headers and shared libraries.  It was not meant to be a complete Slurm cluster with multiple containers on a Docker network.

I would suggest looking at creating a slurmctld container and a slurmd container and then using docker-compose to create a shared volume for the slurm.conf config and running the containers.
