### ISSUE TITLE
Plans to release on PyPi?

### ISSUE THREAD

**Issue by JeffreyThiessen** [PySlurm/pyslurm#97]
Are there any plans to host pyslurm on pypi.python.org? I would love to be able to install it simply with `pip install pyslurm`.

**Comment by giovtorres** [comment]
I'll test it on https://test.pypi.org, as I think I need to tweak the `setup.py` to build the package properly.

**Comment by giovtorres** [comment]
I lost momentum on this over the holidays.  I made some changes to `setup.py` and uploaded to PyPI: https://pypi.python.org/pypi/pyslurm/17.11.0

Give it a try.

**Comment by giovtorres** [comment]
Actually, I think this still needs some work.  I removed the package temporarily.

**Comment by giovtorres** [comment]
https://pypi.python.org/pypi/pyslurm/17.11.0.1

**Comment by JeffreyThiessen** [comment]
Awesome thanks, I'll give it a test run soon.

**Comment by JeffreyThiessen** [comment]
It looks to be installing correctly but the system I am using is running an older version of slurm so I can not confirm if it is fully working. There are plans to upgrade the system to a newer version of slurm in the future so I'll be able to test it end-to-end then.

Installing this way through pip allows me to install pyslurm to a non matching slurm version without warning though, so when running my application, it will not start (as expected). Was this intended? I think it might be better if pip returns an error when trying to install version of pyslurm that is not compatible with the installed version of slurm. 
I don't specifically need this functionality but it might be something to think about in the future.

**Comment by giovtorres** [comment]
Unintended consequence.  The binary wheels are convenient because you won't need a compiler when installing.  The downside is that you would have to specify the version of pyslurm that matches your running version of Slurm, i.e. `pip install pyslurm==17.11.0.1` for example.

Looking at the Slurm mailing list, I've gathered that some users will stick to a version of Slurm for some time, while others upgrade more frequently as new releases become available.  So the pyslurm API has to work for a wide range of Slurm versions.

I think the thing to do is to forego the binary wheels and only upload the source distribution.  This would go through the build/compile step but also catch a mismatched version of slurm and fail to install.

**Comment by rdebroiz** [comment]
Cython can be installed through PyPi. It would be nice IMO to add it as a dependence (rateher than a prerequisite) of pyslurm so it is automatically installed if not found.

**Comment by giovtorres** [comment]
This is fixed now with 17.11.0.5 on pypi, after making some changes to `setup.py` and adding a `MANIFEST.in.`

**Comment by giovtorres** [comment]
Closing this for now.  I'll need to add this step into the Travis builds so that they are automated going forward.  Thanks!
